# Generated by Django 3.1.1 on 2020-09-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200928_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
