# Generated by Django 3.1.1 on 2020-09-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='url',
            new_name='demo_url',
        ),
        migrations.AddField(
            model_name='job',
            name='github_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
