# Generated by Django 3.1.1 on 2020-09-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200928_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='admin_credentials',
            field=models.CharField(default='', max_length=200),
        ),
    ]
