# Generated by Django 3.1.1 on 2020-09-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_admin_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_personal',
            field=models.BooleanField(default=True),
        ),
    ]
