# Generated by Django 3.1.1 on 2020-09-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_is_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='admin_credentials',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='demo_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
