# Generated by Django 3.1.1 on 2020-09-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20200929_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='github_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
