# Generated by Django 3.1.1 on 2020-09-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(default='', max_length=200)),
                ('github_url', models.CharField(blank=True, default='', max_length=200)),
                ('demo_url', models.CharField(blank=True, default='', max_length=200)),
                ('admin_credentials', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.CharField(blank=True, max_length=2000)),
                ('is_personal', models.BooleanField(default=True)),
            ],
        ),
    ]
